import type { ModuleType } from "../audio/modules/types";

export interface ModuleMeta {
  type: ModuleType;
  label: string;
  icon: string;
  accent: string;
  description: string;
  howTo: string;
}

export const MODULE_META: Record<ModuleType, ModuleMeta> = {
  "pitch-shift": {
    type: "pitch-shift",
    label: "Pitch Shift",
    icon: "♪",
    accent: "#4fd8e8",
    description: "Shifts pitch up or down in semitones without changing speed.",
    howTo: "Drag in, set semitones. Stack multiple instances to layer shifts.",
  },
  drive: {
    type: "drive",
    label: "Drive",
    icon: "▲",
    accent: "#ffb400",
    description: "Analog-style warmth (Overdrive) or grit (Distortion) via waveshaping.",
    howTo: "Pick a type, dial Amount for intensity, Tone to tame harshness, Mix to blend with dry.",
  },
  delay: {
    type: "delay",
    label: "Delay",
    icon: "⋰",
    accent: "#b48cff",
    description: "Repeats the signal after a set time, with feedback for repeating echoes.",
    howTo: "Time sets echo spacing, Feedback sets repeat count, Mix sets echo loudness.",
  },
  reverb: {
    type: "reverb",
    label: "Reverb",
    icon: "◈",
    accent: "#5b9dff",
    description: "Simulates the reflections of a physical space.",
    howTo: "Choose a Space size, Mix in how much reflected sound you want.",
  },
  "auto-pan": {
    type: "auto-pan",
    label: "Auto-Pan (8D)",
    icon: "⇄",
    accent: "#ff6ec7",
    description: "Sweeps the sound left-right across the stereo field over time.",
    howTo: "Set Rate for sweep speed; best experienced with headphones.",
  },
  "wow-flutter": {
    type: "wow-flutter",
    label: "Wow & Flutter",
    icon: "∿",
    accent: "#c8e05a",
    description: "Tape/vinyl-style pitch wobble for a lo-fi, imperfect analog feel.",
    howTo: "Rate sets wobble speed, Depth sets how far pitch drifts.",
  },
  vinyl: {
    type: "vinyl",
    label: "Vinyl Crackle",
    icon: "✺",
    accent: "#c98a4b",
    description: "Layers dust, crackle, and pop noise like an old vinyl record.",
    howTo: "Pick a Wear level and Amount to blend the noise bed under the track.",
  },
  chorus: {
    type: "chorus",
    label: "Chorus",
    icon: "≋",
    accent: "#3ddc97",
    description: "Blends the signal with a short, LFO-wobbled delayed copy for a thicker, shimmering tone.",
    howTo: "Rate sets wobble speed, Depth sets how far it wobbles, Mix blends it with dry.",
  },
  flanger: {
    type: "flanger",
    label: "Flanger",
    icon: "∾",
    accent: "#4a90d9",
    description: "A very short modulated delay with feedback, giving a sweeping, metallic whoosh.",
    howTo: "Rate/Depth control the sweep, Feedback intensifies it, Mix blends with dry.",
  },
  phaser: {
    type: "phaser",
    label: "Phaser",
    icon: "◐",
    accent: "#9b6bdb",
    description: "Sweeps a series of notches through the signal for a swirling, psychedelic texture.",
    howTo: "Rate sets sweep speed, Depth sets sweep range, Mix blends with dry.",
  },
  tremolo: {
    type: "tremolo",
    label: "Tremolo",
    icon: "~",
    accent: "#a3d977",
    description: "Rhythmically pulses the volume up and down.",
    howTo: "Rate sets pulse speed, Depth sets how deep the volume dips.",
  },
  compressor: {
    type: "compressor",
    label: "Compressor",
    icon: "▼",
    accent: "#8a99a8",
    description: "Evens out loud and quiet parts by turning down peaks above a threshold.",
    howTo: "Set Threshold and Ratio for how hard it squashes, Attack/Release for timing, Mix to blend.",
  },
  "noise-gate": {
    type: "noise-gate",
    label: "Noise Gate",
    icon: "⊐",
    accent: "#5fa8a0",
    description: "Mutes the signal whenever it drops below a threshold, cutting hiss and bleed between hits.",
    howTo: "Set Threshold for how loud it must be to stay open, Release for how fast it closes.",
  },
  bitcrusher: {
    type: "bitcrusher",
    label: "Bitcrusher",
    icon: "▦",
    accent: "#e0455f",
    description: "Crushes bit depth and sample rate for a harsh, digital lo-fi/8-bit texture.",
    howTo: "Bits controls grit, Rate Reduction controls crunchiness, Mix blends with the clean signal.",
  },
  "ring-mod": {
    type: "ring-mod",
    label: "Ring Modulator",
    icon: "⊗",
    accent: "#3fa9f5",
    description: "Multiplies the signal by a carrier tone for metallic, robotic, bell-like tones.",
    howTo: "Frequency sets the carrier pitch, Mix blends the effect with dry.",
  },
  "stereo-widener": {
    type: "stereo-widener",
    label: "Stereo Widener",
    icon: "↔",
    accent: "#4fd8b8",
    description: "Widens (or narrows) the stereo image by scaling the difference between left and right.",
    howTo: "Width above 100% widens the image, below 100% narrows it toward mono.",
  },
  "auto-wah": {
    type: "auto-wah",
    label: "Auto-Wah",
    icon: "◑",
    accent: "#d4a017",
    description: "A filter that sweeps automatically with the input's loudness, for a talking, funky wah.",
    howTo: "Sensitivity sets how much loudness drives the sweep, Base Freq sets its resting point.",
  },
  harmonizer: {
    type: "harmonizer",
    label: "Harmonizer",
    icon: "♫",
    accent: "#2fb8a6",
    description: "Layers a pitch-shifted voice under the dry signal for harmony/shimmer, unlike Pitch Shift's full replace.",
    howTo: "Semitones sets the harmony interval (default +12, an octave up), Mix blends it in.",
  },
  "multiband-distortion": {
    type: "multiband-distortion",
    label: "Multiband Distortion",
    icon: "△",
    accent: "#d9732e",
    description: "Applies independent distortion to low, mid, and high bands so bass can stay clean while highs get grit.",
    howTo: "Dial in Low/Mid/High Amount separately, Mix blends the result with dry.",
  },
  slapback: {
    type: "slapback",
    label: "Slapback Delay",
    icon: "»",
    accent: "#d68fd6",
    description: "A single short echo with no feedback, for classic rockabilly-style doubling.",
    howTo: "Time sets the echo spacing (short, 60-150ms works best), Mix sets its loudness.",
  },
  "reverse-swell": {
    type: "reverse-swell",
    label: "Reverse Swell",
    icon: "⤴",
    accent: "#7fc8e8",
    description: "A rising reverb tail that swells in, approximating a reverse-reverb effect in real time.",
    howTo: "Length sets how long the swell takes to build, Mix blends it with dry.",
  },
  freeze: {
    type: "freeze",
    label: "Freeze",
    icon: "❄",
    accent: "#a8e0f0",
    description: "Captures a short moment of audio and sustains it indefinitely while enabled.",
    howTo: "Enable to freeze whatever's playing right now; disable to return to normal playback.",
  },
  telephone: {
    type: "telephone",
    label: "Telephone Filter",
    icon: "☎",
    accent: "#9a8f3c",
    description: "Band-limits the signal to a narrow telephone/AM-radio range with light crunch.",
    howTo: "Crunch adds grit on top of the band-limiting, Mix blends with the full-range dry signal.",
  },
  sidechain: {
    type: "sidechain",
    label: "Sidechain Ducking",
    icon: "⇊",
    accent: "#ff8c42",
    description: "Rhythmically ducks the volume like a sidechain-compressed \"pump\" effect.",
    howTo: "Rate sets the pump speed, Depth sets how far it ducks each time.",
  },
  formant: {
    type: "formant",
    label: "Formant Filter",
    icon: "◎",
    accent: "#c56cf0",
    description: "Colors the tone with vowel-like resonances for a talk-box/robotic vocal character.",
    howTo: "Pick a Vowel (A/E/I/O/U), Mix blends the colored tone with dry.",
  },
  stutter: {
    type: "stutter",
    label: "Granular Stutter",
    icon: "▤",
    accent: "#39ff6a",
    description: "Captures a short window of audio and loops it rapidly for a rhythmic glitch/stutter effect.",
    howTo: "Window sets the captured slice length; enable to trigger the stutter, disable to resume normal playback.",
  },
  cabinet: {
    type: "cabinet",
    label: "Cabinet Sim",
    icon: "▥",
    accent: "#b87333",
    description: "Colors the tone like it's playing through a small speaker, phone earpiece, or AM radio.",
    howTo: "Pick a Type, Mix blends the colored tone with the full-range dry signal.",
  },
  "reverse-delay": {
    type: "reverse-delay",
    label: "Reverse Delay",
    icon: "↺",
    accent: "#7e6fd8",
    description: "Records each echo and plays it back backwards, for a swelling, otherworldly repeat.",
    howTo: "Time sets the length of each reversed chunk, Feedback layers repeats, Mix blends with dry.",
  },
};

export const MODULE_TYPES: readonly ModuleType[] = [
  "pitch-shift",
  "drive",
  "delay",
  "reverb",
  "auto-pan",
  "wow-flutter",
  "vinyl",
  "chorus",
  "flanger",
  "phaser",
  "tremolo",
  "compressor",
  "noise-gate",
  "bitcrusher",
  "ring-mod",
  "stereo-widener",
  "auto-wah",
  "harmonizer",
  "multiband-distortion",
  "slapback",
  "reverse-swell",
  "freeze",
  "telephone",
  "sidechain",
  "formant",
  "stutter",
  "cabinet",
  "reverse-delay",
];
